version: "3.8"

# Volume - это папка с файлами, которая лежит за пределами контейнеров.
volumes:
  postgres-data:
  pictures:

services:
  db:
    # собираем сервис из образа Postgres
    image: postgres:14
    # пробрасываем данные для подключения к БД в контейнер
    env_file:
      - ./.env
    # из файла .env далее сформируем строку для подключения к БД
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
    # сохраняем данные постгреса(про все миграции) вне контейнера, чтобы они не потерялись при пересборке
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    # внешний порт : внутренний порт
    ports:
      - 5432:5432
    container_name: pictures-db

  server:
    # папка, в которой лежит Dockerfile
    build: ./
    # здесь будут лежать файлы клиента внутри контейнера
    working_dir: /app
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
    # сервер не будет запущен пока не будет запущена БД
    depends_on:
      - db
    # сохраняем файлы с картинками, чтобы они не потерялись при пересборке
    volumes:
      - pictures:/app/public/img
    # порт 3000 контейнера будет проксироваться(передаваться) на порт 3000 хоста
    # внешний - порт хоста : внутренний - порт контейнера
    ports:
      - 3000:${PORT}
    container_name: pictures-app-server
